### ISSUE TITLE
Can I not serialise RuntimeType?

### ISSUE THREAD

**Issue by wusong4988398** [ProductiveRage/DanSerialiser#2]
Can not serialise pointer fields: m_cache on RuntimeType
![image](https://user-images.githubusercontent.com/10472968/105936670-15f68780-608f-11eb-8f0e-f9a87e8ba5bf.png)

**Comment by ProductiveRage** [comment]
Sorry it's taken me a few days to get to this, I saw your issue through my email and then forgot all about it!

You're essentially using the correct approach by passing a Type Converter to the Serialise method but I don't recognise the name `RuntimeTypeConverter` - is that one that you have written yourself?

The reason that the serialiser can't deal with pointers is that it would be insufficient to simply include the pointer value in the serialised data because when it was deserialised again, that memory location would no longer be valid! And I don't think that it's possible to inspect the memory location that the pointer points to because we can't know for sure how much data there is that that must be included! (And the deserialisation work would be awkward even if it _was_ possible because we'd have to pin some memory, copy the serialised data that the pointer pointed at and then create a new pointer instance that pointed at the memory location in the process that had done the deserialising!)

The good news, though, is that there is a type converter available in the DanSerialiser package already called (imaginatively) `TypeTypeConverter` (because it is a Type Converter for Types!) - `RuntimeType` is a concrete specialisation of the abstract class `Type` and so the `TypeTypeConverter` will work with it.

What it does is that it serialises the value as a string, taking the type's "AssemblyQualifiedName" and then deserialises by taking that string and calling "Type.GetType(..)". As it includes the full assembly information as well as the type name, you _may_ encounter problems if you try to deserialise types that were serialised from an older version number of your assembly. Or you might get problems if you're passing system types between .NET Framework and .NET Core applications because the assembly names changed for some of them.

However, this should be a good place to start and if you _do_ hit the assembly-name-based problems above then I'm sure that we could come up with something that would do the job in your particular scenario.

To illustrate it working, first is an example a little bit like yours that will **not** work:

```
var value = typeof(string);
var serialisedData = BinarySerialisation.Serialise(value);
var clone = BinarySerialisation.Deserialise<Type>(serialisedData);
```

.. and here is a version that *will* work:

```
var typeConverters = new[] { TypeTypeConverter.Instance };

var value = typeof(string);
var serialisedData = BinarySerialisation.Serialise(value, typeConverters);
var clone = BinarySerialisation.Deserialise<Type>(serialisedData, typeConverters);
```

Note that you have to specify the same type converters in the Serialise _and_ Deserialise calls.

**Comment by ProductiveRage** [comment]
Hopefully this addresses the problem? Feel free to re-open if you disagree.
